[tool.poetry]
name = "pystart"
version = "0.1.0"
description = "pystart project"
authors = ["Dan Park <dan.park.primary@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
